from sqlalchemy import Column, Integer, String, Text
from app.db.base_class import Base

class Book(Base):
    """
    SQLAlchemy ORM model for the 'books' table. [cite: 20]
    """
    id = Column(Integer, primary_key=True, index=True)
    title = Column(String, index=True, nullable=False)
    author = Column(String, index=True, nullable=False)
    genre = Column(String, index=True)
    year_published = Column(Integer)
    # The summary will be generated by the Llama3 model
    summary = Column(Text, default="Summary pending generation.")
    
    def __repr__(self):
        return f"<Book(title='{self.title}', author='{self.author}')>"